In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datasets import load_dataset
# Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

# Data Cleaning
df["job_posted_date"]=pd.to_datetime(df["job_posted_date"])

In [16]:
df_cleaned=df[pd.notna(df['salary_year_avg'])].copy()

def protected_salary(salary):
    return salary*1.03

df_cleaned['salary_year_inflated'] = df_cleaned['salary_year_avg'].apply(protected_salary)

df_cleaned[['salary_year_inflated', 'salary_year_avg']].head()

     salary_year_inflated  salary_year_avg
28              112785.00         109500.0
77              144200.00         140000.0
92              123600.00         120000.0
100             235068.66         228222.0
109              91670.00          89000.0

In [17]:
# Using a lambda function

df_cleaned['salary_year_avg'].apply(lambda x: x*1.03).head()

28     112785.00
77     144200.00
92     123600.00
100    235068.66
109     91670.00
Name: salary_year_avg, dtype: float64

In [43]:
df_cleaned['job_skills'].iloc[0]

"['gdpr', 'excel']"

In [ ]:
import ast

ast.literal_eval(df_cleaned['job_skills'])

['gdpr', 'excel']

In [44]:
pd.isna(df_cleaned['job_skills'])

28        False
77        False
92        False
100       False
109       False
          ...
785624    False
785641     True
785648    False
785682    False
785692    False
Name: job_skills, Length: 22003, dtype: bool

In [55]:
def clean_skills(skills):
    if pd.isna(skills):
        return []
    else:
        return ast.literal_eval(skills)

df_cleaned['job_skills_cleaned'] = df_cleaned['job_skills'].apply(clean_skills)


df_cleaned['job_skills'].apply(lambda x: [] if pd.isna(x) else ast.literal_eval(x)).head()

28                                         [gdpr, excel]
77     [mongodb, mongodb, python, r, sql, mysql, mari...
92                                         [sql, python]
100                            [sql, r, python, express]
109                        [python, r, alteryx, tableau]
Name: job_skills, dtype: object

Make another column named projected salary 2, where I will assume that senior roles will get 5 percent increase and others will get 3 percent.
----------------------------------------------------------------------------------------------

In [59]:
def projected_salary_2(row):
    if pd.isna(row['job_title_short']) or pd.isna(row['job_skills']):
        return []
    else:    
        
        if 'senior' in row['job_title_short'].lower():
            salary = row['salary_year_avg']
            return salary * 1.05

        else:
            salary = row['salary_year_avg']
            return salary * 1.03

df_cleaned['salary_year_inflated_2'] = df_cleaned.apply(projected_salary_2, axis=1)

df_cleaned[['salary_year_inflated_2', 'salary_year_avg', 'job_title_short', 'salary_year_inflated']].sample(10)

,salary_year_inflated_2,salary_year_avg,job_title_short,salary_year_inflated
744180,[],90000.0,Data Engineer,92700.00
219418,159650.0,155000.0,Data Analyst,159650.00
509893,90846.0,88200.0,Data Analyst,90846.00
606333,215270.0,209000.0,Data Scientist,215270.00
522497,126175.0,122500.0,Data Scientist,126175.00
106518,110725.0,107500.0,Business Analyst,110725.00
21349,116733.75,111175.0,Senior Data Analyst,114510.25
178942,154875.0,147500.0,Senior Data Engineer,151925.00
762928,56650.0,55000.0,Data Analyst,56650.00
259069,103000.0,100000.0,Data Scientist,103000.00