In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datasets import load_dataset
# Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

# Data Cleaning
df["job_posted_date"]=pd.to_datetime(df["job_posted_date"])
df.loc[:10,"salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [5]:
median_salary_yearly= df["salary_year_avg"].median()
median_salary_hourly= df["salary_hour_avg"].median()
df_filled=df
df_filled["salary_hour_avg"]=df_filled["salary_hour_avg"].fillna(median_salary_hourly)
df_filled["salary_year_avg"]=df_filled["salary_year_avg"].fillna(median_salary_yearly)
df_filled.loc[:10,"salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [6]:
df.loc[:10,"salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [10]:
# Removing Duplicates
print("Lenght of the dataset before removing duplicates: ",len(df_filled))
df_unique=df_filled
df_unique=df_unique.drop_duplicates()
print("Lenght of the dataset after removing duplicates: ",len(df_unique))
print("Rows removed: ",len(df_filled)-len(df_unique))

Lenght of the dataset before removing duplicates:  785741
Lenght of the dataset after removing duplicates:  785640
Rows removed:  101

In [11]:
df_unique=df_unique.drop_duplicates(subset=['job_title','company_name'])
print("Lenght of the dataset before removing duplicates: ",len(df_filled))
print("Lenght of the dataset after removing duplicates: ",len(df_unique))
print("Rows removed: ",len(df_filled)-len(df_unique))

Lenght of the dataset before removing duplicates:  785741
Lenght of the dataset after removing duplicates:  508042
Rows removed:  277699